### ISSUE TITLE
Return instance of `Todo` instead of `User` where required

### ISSUE THREAD

**Issue by prmsrswt** [prmsrswt/graphql-todo-server#2]
Currently `addTodo`, `toggleTodo` and `removeTodo` returns whole `User` but it should be sufficient to return `Todo` at maximum.

**Comment by hosseinnedaee** [comment]
Hi @prmsrswt, I wanna work on this issue. could you please describe more about the issue?

**Comment by prmsrswt** [comment]
In the GraphQL schema we have two custom types `Todo` and `User`. We also have a custom type `TodoResponse` which is returned for each `addTodo`, `toggleTodo` and `removeTodo`. `TodoResponse` contains the field `user` which of type `User`. So when for example say, we run the mutation `addTodo`, we need to return whole user-data. What we can do is instead return only the `Todo` which we have added.

So the goal here is to first add a new field in `TodoResponse` called `todo` of type `Todo` and modify the resolvers of `addTodo`, `toggleTodo` and `removeTodo` accordingly.

**Comment by HarisSpahija** [comment]
I updated @drakeloud his pullrequest with requested changes in #7
